name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make install
        run: make install

      - name: Make lint
        run: make lint
        env:
          DEFAULT_BRANCH: GACTIONS
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
